version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: estatemap_backend
    restart: always
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    environment:
      DEBUG: "False"

      SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${SERVER_IP}:5432/${DB_NAME}

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: "False"
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    ports:
      - "8000:8000"
    networks:
      - estatemap_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: estatemap_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - estatemap_network

volumes:
  static_volume:
  media_volume:

networks:
  estatemap_network:
    driver: bridge
